name = "cfmatchmaking"
account_id = "312be46039aca8bf23a26050451a3bda"
main = "src/index.js"
compatibility_date = "2025-08-31"

[[durable_objects.bindings]]
name = "MATCHMAKING_QUEUE"
class_name = "MatchmakingQueue"

[[migrations]]
tag = "v1"
new_classes = ["MatchmakingQueue"]
